/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ConsumoControlador;
import controlador.PagoControlador;
import java.sql.Date;
import javax.swing.JInternalFrame;
import modelo.Consumo;
import modelo.Pago;
import modelo.dao.ConsumoDAO;
import modelo.dao.PagoDAO;
import static vista.FormPrincipal.ventanaprincipal;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Dante_Sanchez
 */
public class FormReservacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form nuevoreservaacion
     */
    public FormReservacion() {
        initComponents();
        
        //inicio.lblusuario.setText("Usuario: " + modeloAdmin.getUsuario());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listareserva = new javax.swing.JTable();
        btnrealizarpago = new javax.swing.JButton();
        btnagregarconsumo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ImageIcon icon  = new ImageIcon(getClass().getResource("/imagenes/form_reserva.jpg"));
        Image image = icon.getImage();
        jPanel2 = new javax.swing.JPanel() {
            public void  paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btnlimpiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        txtidhabitacion = new javax.swing.JTextField();
        dcfechasalida = new com.toedter.calendar.JDateChooser();
        dcfechaingreso = new com.toedter.calendar.JDateChooser();
        txtcodigoreserva = new javax.swing.JTextField();
        txtadministrador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboestadoreserva = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtprecioreserva = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnbuscarcliente = new javax.swing.JButton();
        btnbuscarhabitacion = new javax.swing.JButton();
        txtidempleado = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        txtidreservacion = new javax.swing.JTextField();
        txthabitacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setTitle("RESERVACIONES");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        listareserva.setBackground(new java.awt.Color(0, 204, 153));
        listareserva.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        listareserva.setForeground(new java.awt.Color(255, 255, 255));
        listareserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listareserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listareservaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listareserva);

        btnrealizarpago.setBackground(new java.awt.Color(51, 51, 51));
        btnrealizarpago.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnrealizarpago.setForeground(new java.awt.Color(255, 255, 153));
        btnrealizarpago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnpagar.png"))); // NOI18N
        btnrealizarpago.setText("Pagar");
        btnrealizarpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrealizarpagoActionPerformed(evt);
            }
        });

        btnagregarconsumo.setBackground(new java.awt.Color(51, 51, 51));
        btnagregarconsumo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnagregarconsumo.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarconsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnconsumo2.png"))); // NOI18N
        btnagregarconsumo.setText("Agregar Consumos");
        btnagregarconsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarconsumoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LISTA DE RESERVACIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnagregarconsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrealizarpago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrealizarpago)
                    .addComponent(btnagregarconsumo))
                .addGap(26, 26, 26))
        );

        btnlimpiar.setBackground(new java.awt.Color(51, 51, 51));
        btnlimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 153));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");

        btneliminar.setBackground(new java.awt.Color(51, 51, 51));
        btneliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 153));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");

        btnmodificar.setBackground(new java.awt.Color(51, 51, 51));
        btnmodificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 153));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(51, 51, 51));
        btnguardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 153));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");

        txtidhabitacion.setBackground(new java.awt.Color(255, 51, 0));

        dcfechasalida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        dcfechaingreso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtcodigoreserva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtadministrador.setEditable(false);
        txtadministrador.setBackground(new java.awt.Color(0, 102, 153));
        txtadministrador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtadministrador.setForeground(new java.awt.Color(255, 255, 255));
        txtadministrador.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario encargado de Reserva:");

        txtcliente.setEditable(false);
        txtcliente.setBackground(new java.awt.Color(204, 204, 204));
        txtcliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcliente.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código de Reserva :");

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente :");

        cboestadoreserva.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cboestadoreserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagada", "Reservada" }));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVACION");

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Estado de reserva :");

        txtprecioreserva.setEditable(false);
        txtprecioreserva.setBackground(new java.awt.Color(204, 204, 204));
        txtprecioreserva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtprecioreserva.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio :");

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de salida :");

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de ingreso :");

        btnbuscarcliente.setBackground(new java.awt.Color(51, 51, 51));
        btnbuscarcliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbuscarcliente.setForeground(new java.awt.Color(255, 255, 153));
        btnbuscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnbuscarcliente.setText("Buscar cliente");
        btnbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclienteActionPerformed(evt);
            }
        });

        btnbuscarhabitacion.setBackground(new java.awt.Color(51, 51, 51));
        btnbuscarhabitacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbuscarhabitacion.setForeground(new java.awt.Color(255, 255, 153));
        btnbuscarhabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnbuscarhabitacion.setText("Buscar habitación");
        btnbuscarhabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarhabitacionActionPerformed(evt);
            }
        });

        txtidempleado.setEditable(false);
        txtidempleado.setBackground(new java.awt.Color(255, 51, 0));
        txtidempleado.setFocusable(false);

        txtidcliente.setBackground(new java.awt.Color(255, 51, 0));

        txtidreservacion.setBackground(new java.awt.Color(255, 51, 0));

        txthabitacion.setEditable(false);
        txthabitacion.setBackground(new java.awt.Color(204, 204, 204));
        txthabitacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txthabitacion.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Habitación :");

        btnbuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcodigoreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtidreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcfechasalida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecioreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboestadoreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txthabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodificar)
                .addGap(34, 34, 34)
                .addComponent(btneliminar)
                .addGap(37, 37, 37)
                .addComponent(btnlimpiar)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcodigoreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar)
                    .addComponent(txtidreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscarhabitacion)
                    .addComponent(txthabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarcliente))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dcfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dcfechasalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtprecioreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboestadoreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar)
                    .addComponent(btnlimpiar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarhabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarhabitacionActionPerformed
        // TODO add your handling code here:
        FormListaHabitacion listahabitacion = new FormListaHabitacion();
        listahabitacion.toFront();
        listahabitacion.setVisible(true);
    }//GEN-LAST:event_btnbuscarhabitacionActionPerformed

    private void btnbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclienteActionPerformed
        // TODO add your handling code here:
        FormListaCliente listacliente = new FormListaCliente();
        listacliente.toFront();
        listacliente.setVisible(true);
    }//GEN-LAST:event_btnbuscarclienteActionPerformed

    private void btnagregarconsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarconsumoActionPerformed
        // TODO add your handling code here:
        
        int fila = listareserva.getSelectedRow();
        ConsumoControlador.idreserva = listareserva.getValueAt(fila, 0).toString();
        ConsumoControlador.cliente = listareserva.getValueAt(fila, 4).toString();
        
        Consumo modeloConsumo = new Consumo();
        ConsumoDAO modeloConsumoDAO = new ConsumoDAO();
        FormConsumos vistaConsumo = new FormConsumos();
        
        ConsumoControlador controladorConsumo = new ConsumoControlador(modeloConsumo, modeloConsumoDAO, vistaConsumo);
        controladorConsumo.iniciar();
        //vistaConsumo.setVisible(true);
        
        FormPrincipal.ventanaprincipal.add(vistaConsumo);
        vistaConsumo.toFront();
        vistaConsumo.setVisible(true);
        
        CentrarVentanaInterna(vistaConsumo);
        
        
        
        /*
        FormConsumos vistaConsumo = new FormConsumos();
        FormPrincipal.ventanaprincipal.add(vistaConsumo);
        vistaConsumo.toFront();
        vistaConsumo.setVisible(true);
        CentrarVentanaInterna(vistaConsumo);
        */
        
        
         
        /*
        FormConsumos form = new FormConsumos();
        FormPrincipal.ventanaprincipal.add(form);
        form.toFront();
        form.setVisible(true);
        */
        
    }//GEN-LAST:event_btnagregarconsumoActionPerformed

    private void listareservaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listareservaMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
         
       //habilitar botones
        this.btnrealizarpago.setEnabled(true);
        this.btnagregarconsumo.setEnabled(true);
        
        
        int fila = listareserva.rowAtPoint(evt.getPoint());

        txtidreservacion.setText(listareserva.getValueAt(fila, 0).toString());
        
        txtidhabitacion.setText(listareserva.getValueAt(fila, 1).toString());
        txthabitacion.setText(listareserva.getValueAt(fila, 2).toString());
        
        txtidcliente.setText(listareserva.getValueAt(fila, 3).toString());
        txtcliente.setText(listareserva.getValueAt(fila, 4).toString());
        
        txtidempleado.setText(listareserva.getValueAt(fila, 5).toString());
        txtadministrador.setText(listareserva.getValueAt(fila, 6).toString());
        
        txtcodigoreserva.setText(listareserva.getValueAt(fila, 7).toString());
        
        dcfechaingreso.setDate(Date.valueOf(listareserva.getValueAt(fila, 8).toString()));
        dcfechasalida.setDate(Date.valueOf(listareserva.getValueAt(fila, 9).toString()));
        
        txtprecioreserva.setText(listareserva.getValueAt(fila, 10).toString());
        
        cboestadoreserva.setSelectedItem(listareserva.getValueAt(fila, 11).toString());
        

        
        
        }
        
    }//GEN-LAST:event_listareservaMousePressed

    private void btnrealizarpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealizarpagoActionPerformed
        // TODO add your handling code here:
        
        //
        int fila = listareserva.getSelectedRow();
        PagoControlador.idreserva = listareserva.getValueAt(fila, 0).toString();
        PagoControlador.cliente = listareserva.getValueAt(fila, 4).toString();
        PagoControlador.totalreserva =Double.parseDouble( listareserva.getValueAt(fila, 10).toString());
        
        PagoControlador.idhabitacion = listareserva.getValueAt(fila, 1).toString();
        PagoControlador.habitacion = listareserva.getValueAt(fila, 2).toString();
        //
        
        
        
        Pago modeloPago = new Pago();
        PagoDAO modeloPagoDAO = new PagoDAO();
        FormPago vistaPago = new FormPago();
        
        PagoControlador controladorPago = new PagoControlador(modeloPago, modeloPagoDAO, vistaPago);
        controladorPago.iniciar();
        //vistaConsumo.setVisible(true);
        
        FormPrincipal.ventanaprincipal.add(vistaPago);
        vistaPago.toFront();
        vistaPago.setVisible(true);
        
        CentrarVentanaInterna(vistaPago);
    }//GEN-LAST:event_btnrealizarpagoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    
        public void CentrarVentanaInterna(JInternalFrame internalFrame) {
        
        int x = (ventanaprincipal.getWidth() / 2) - internalFrame.getWidth() /2;
        int y = (ventanaprincipal.getHeight()/ 2) - internalFrame.getHeight()/2;
        
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
            
        }else {
            ventanaprincipal.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnagregarconsumo;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btnbuscarcliente;
    public javax.swing.JButton btnbuscarhabitacion;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnlimpiar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JButton btnrealizarpago;
    public javax.swing.JComboBox<String> cboestadoreserva;
    public com.toedter.calendar.JDateChooser dcfechaingreso;
    public com.toedter.calendar.JDateChooser dcfechasalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable listareserva;
    public static javax.swing.JTextField txtadministrador;
    public static javax.swing.JTextField txtcliente;
    public javax.swing.JTextField txtcodigoreserva;
    public static javax.swing.JTextField txthabitacion;
    public static javax.swing.JTextField txtidcliente;
    public static javax.swing.JTextField txtidempleado;
    public static javax.swing.JTextField txtidhabitacion;
    public javax.swing.JTextField txtidreservacion;
    public static javax.swing.JTextField txtprecioreserva;
    // End of variables declaration//GEN-END:variables
}
