/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ClienteControlador;
import controlador.EmpleadoControlador;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

import java.awt.Image;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Empleado;
import modelo.dao.ClienteDAO;
import modelo.dao.EmpleadoDAO;

/**
 *
 * @author Dante_Sanchez
 */
public class FormEmpleado extends javax.swing.JInternalFrame  {

       
    /**
     * Creates new form ClienteNuevo
     */
    public FormEmpleado() {
        initComponents();
        

    }

    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon  = new ImageIcon(getClass().getResource("/imagenes/fondo_ (1).jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel() {
            public void  paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        txtmaterno = new javax.swing.JTextField();
        cbopuesto = new javax.swing.JComboBox<>();
        txtpaterno = new javax.swing.JTextField();
        puesto = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        codigodeempleado = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        correo = new javax.swing.JLabel();
        btnmodificar = new javax.swing.JButton();
        telefono = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        materno = new javax.swing.JLabel();
        txtidpersona = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        paterno = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        txtcodigodeempleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        sueldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaempleado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("EMPLEADOS");

        txtmaterno.setBackground(new java.awt.Color(255, 255, 204));
        txtmaterno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaternoActionPerformed(evt);
            }
        });

        cbopuesto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbopuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Animador", "Ama de llaves", "Asistente de Direccion", "Botones", "Camarero", "Chef", "Cocinero", "Concierge", "Director General", "Elevadorista", "Garrotero", "Gerente de Bar", "Gerente de Eventos", "Gerente de Recepcion", "Hostess", "Limpieza", "Mantenimiento", "Mesero", "Pluma", "Recepcionista", "Seguridad" }));

        txtpaterno.setBackground(new java.awt.Color(255, 255, 204));
        txtpaterno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtpaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaternoActionPerformed(evt);
            }
        });

        puesto.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        puesto.setForeground(new java.awt.Color(255, 255, 255));
        puesto.setText("Puesto:");

        txtnombre.setBackground(new java.awt.Color(255, 255, 204));
        txtnombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        btnlimpiar.setBackground(new java.awt.Color(51, 51, 51));
        btnlimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 153));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");

        codigodeempleado.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        codigodeempleado.setForeground(new java.awt.Color(255, 255, 255));
        codigodeempleado.setText("Codigo de Empleado:");

        btneliminar.setBackground(new java.awt.Color(51, 51, 51));
        btneliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 153));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");

        correo.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        correo.setForeground(new java.awt.Color(255, 255, 255));
        correo.setText("Correo:");

        btnmodificar.setBackground(new java.awt.Color(51, 51, 51));
        btnmodificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 153));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnmodificar.setText("Modificar");

        telefono.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setText("Telefono:");

        btnguardar.setBackground(new java.awt.Color(51, 51, 51));
        btnguardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 153));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");

        materno.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        materno.setForeground(new java.awt.Color(255, 255, 255));
        materno.setText("Apellido Materno:");

        txtidpersona.setBackground(new java.awt.Color(255, 51, 51));
        txtidpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpersonaActionPerformed(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnbuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 153));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnbuscar.setText("Buscar");

        paterno.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        paterno.setForeground(new java.awt.Color(255, 255, 255));
        paterno.setText("Apellido Paterno:");

        nombre.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre:");

        txtcodigodeempleado.setBackground(new java.awt.Color(204, 204, 255));
        txtcodigodeempleado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtcodigodeempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigodeempleadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("REGISTRO DE EMPLEADOS");

        txtcorreo.setBackground(new java.awt.Color(255, 255, 204));
        txtcorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        txtsueldo.setBackground(new java.awt.Color(255, 255, 204));
        txtsueldo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txttelefono.setBackground(new java.awt.Color(255, 255, 204));
        txttelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        sueldo.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        sueldo.setForeground(new java.awt.Color(255, 255, 255));
        sueldo.setText("Sueldo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(puesto)
                            .addComponent(sueldo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 312, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paterno)
                            .addComponent(materno)
                            .addComponent(nombre)
                            .addComponent(codigodeempleado))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodigodeempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telefono)
                                    .addComponent(correo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnguardar)
                .addGap(27, 27, 27)
                .addComponent(btnmodificar)
                .addGap(27, 27, 27)
                .addComponent(btneliminar)
                .addGap(26, 26, 26)
                .addComponent(btnlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigodeempleado)
                    .addComponent(txtcodigodeempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar)
                    .addComponent(txtidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paterno)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefono)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correo)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materno)
                    .addComponent(txtmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(puesto)
                    .addComponent(cbopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldo)
                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar)
                    .addComponent(btnlimpiar))
                .addGap(44, 44, 44))
        );

        tablaempleado.setBackground(new java.awt.Color(204, 255, 153));
        tablaempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaempleadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaempleado);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("LISTA DE EMPLEADOS REGISTRADOS :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaternoActionPerformed

    private void txtpaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaternoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtidpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpersonaActionPerformed

    private void txtcodigodeempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigodeempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigodeempleadoActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void tablaempleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaempleadoMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            
        int fila = tablaempleado.rowAtPoint(evt.getPoint());

        txtidpersona.setText(tablaempleado.getValueAt(fila, 0).toString());
        txtcodigodeempleado.setText(tablaempleado.getValueAt(fila, 1).toString());
        
        txtnombre.setText(tablaempleado.getValueAt(fila, 2).toString());
        txtpaterno.setText(tablaempleado.getValueAt(fila, 3).toString());
        txtmaterno.setText(tablaempleado.getValueAt(fila, 4).toString());

        txttelefono.setText(tablaempleado.getValueAt(fila, 5).toString());
        txtcorreo.setText(tablaempleado.getValueAt(fila, 6).toString());
        
        cbopuesto.setSelectedItem(tablaempleado.getValueAt(fila, 7).toString());
        txtsueldo.setText(tablaempleado.getValueAt(fila, 8).toString());
        
        
        }
    }//GEN-LAST:event_tablaempleadoMousePressed

    

        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnlimpiar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JComboBox<String> cbopuesto;
    public javax.swing.JLabel codigodeempleado;
    public javax.swing.JLabel correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel materno;
    public javax.swing.JLabel nombre;
    public javax.swing.JLabel paterno;
    public javax.swing.JLabel puesto;
    public javax.swing.JLabel sueldo;
    public javax.swing.JTable tablaempleado;
    public javax.swing.JLabel telefono;
    public javax.swing.JTextField txtcodigodeempleado;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtidpersona;
    public javax.swing.JTextField txtmaterno;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtpaterno;
    public javax.swing.JTextField txtsueldo;
    public javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
