/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AdminControlador;
import controlador.ClienteControlador;
import controlador.EmpleadoControlador;
import controlador.HabitacionControlador;
import controlador.ReservaControlador;
import controlador.ServicioControlador;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import modelo.Administrador;
import modelo.Cliente;
import modelo.Conexion;
import modelo.Empleado;
import modelo.Habitacion;
import modelo.Reservacion;
import modelo.Servicio;
import modelo.dao.AdministradorDAO;
import modelo.dao.ClienteDAO;
import modelo.dao.EmpleadoDAO;
import modelo.dao.HabitacionDAO;
import modelo.dao.ReservacionDAO;
import modelo.dao.ServicioDAO;

import vista.FormPrincipal;



/**
 *
 * @author Dante_Sanchez
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setExtendedState(FormPrincipal.MAXIMIZED_BOTH);
        this.lblidempleado.setVisible(false);
        //setResizable(false);
        
     
        
        
        //setResizable(false);
        
        //setTitle("Hotel Tesco");
        
        
        /*
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/habitacion.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon  = new ImageIcon(getClass().getResource("/imagenes/principal2.jpg"));
        Image image = icon.getImage();
        ventanaprincipal = new javax.swing.JDesktopPane() {

            public void  paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        lblidpersona = new javax.swing.JLabel();
        lblusuario2 = new javax.swing.JLabel();
        lblidempleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblacceso = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblacceso1 = new javax.swing.JLabel();
        menuprincipal = new javax.swing.JMenuBar();
        menupersonal = new javax.swing.JMenu();
        submenuempleados = new javax.swing.JMenuItem();
        submenuadmin = new javax.swing.JMenuItem();
        menureservaciones = new javax.swing.JMenu();
        submenuclientes = new javax.swing.JMenuItem();
        submenureserva = new javax.swing.JMenuItem();
        menuservicios = new javax.swing.JMenu();
        submenuhabitacion = new javax.swing.JMenuItem();
        submenuservextra = new javax.swing.JMenuItem();
        menuacercade = new javax.swing.JMenu();
        submenuintegrantes = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HOTEL AZTECA TECH ⭐");
        setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        setUndecorated(true);

        ventanaprincipal.setBackground(new java.awt.Color(51, 51, 51));

        lblidpersona.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblidpersona.setForeground(new java.awt.Color(255, 255, 255));
        lblidpersona.setText("Sesión Actual::");
        ventanaprincipal.add(lblidpersona);
        lblidpersona.setBounds(10, 10, 110, 20);

        lblusuario2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblusuario2.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario2.setText("Usuario:");
        ventanaprincipal.add(lblusuario2);
        lblusuario2.setBounds(10, 30, 50, 20);

        lblidempleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblidempleado.setForeground(new java.awt.Color(255, 255, 255));
        lblidempleado.setText("idempleado");
        ventanaprincipal.add(lblidempleado);
        lblidempleado.setBounds(10, 80, 120, 20);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("HOTEL AZTECA");
        ventanaprincipal.add(jLabel1);
        jLabel1.setBounds(550, 20, 300, 30);

        lblacceso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblacceso.setForeground(new java.awt.Color(255, 255, 255));
        lblacceso.setText("aqui aparece acceso");
        ventanaprincipal.add(lblacceso);
        lblacceso.setBounds(70, 50, 230, 20);

        lblusuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario.setText("aqui aparece usuario");
        ventanaprincipal.add(lblusuario);
        lblusuario.setBounds(70, 30, 230, 20);

        lblacceso1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblacceso1.setForeground(new java.awt.Color(255, 255, 255));
        lblacceso1.setText("Nivel:");
        ventanaprincipal.add(lblacceso1);
        lblacceso1.setBounds(30, 50, 30, 20);

        menupersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal.png"))); // NOI18N
        menupersonal.setText("Personal Hotel          ");
        menupersonal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        submenuempleados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenuempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        submenuempleados.setText("Empleados");
        submenuempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuempleadosActionPerformed(evt);
            }
        });
        menupersonal.add(submenuempleados);

        submenuadmin.setBackground(new java.awt.Color(255, 51, 51));
        submenuadmin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenuadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        submenuadmin.setText("Administradores");
        submenuadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuadminActionPerformed(evt);
            }
        });
        menupersonal.add(submenuadmin);

        menuprincipal.add(menupersonal);

        menureservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservas.png"))); // NOI18N
        menureservaciones.setText("Reservaciones          ");
        menureservaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        submenuclientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenuclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        submenuclientes.setText("Clientes");
        submenuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuclientesActionPerformed(evt);
            }
        });
        menureservaciones.add(submenuclientes);

        submenureserva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenureserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reserva.png"))); // NOI18N
        submenureserva.setText("Reservación");
        submenureserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenureservaActionPerformed(evt);
            }
        });
        menureservaciones.add(submenureserva);

        menuprincipal.add(menureservaciones);

        menuservicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servic.png"))); // NOI18N
        menuservicios.setText("Servicios          ");
        menuservicios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        submenuhabitacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenuhabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habitacion.png"))); // NOI18N
        submenuhabitacion.setText("Habitaciones");
        submenuhabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuhabitacionActionPerformed(evt);
            }
        });
        menuservicios.add(submenuhabitacion);

        submenuservextra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenuservextra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicios.png"))); // NOI18N
        submenuservextra.setText("Servicios Extra");
        submenuservextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuservextraActionPerformed(evt);
            }
        });
        menuservicios.add(submenuservextra);

        menuprincipal.add(menuservicios);

        menuacercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acercade.png"))); // NOI18N
        menuacercade.setText("Acerca de          ");
        menuacercade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        submenuintegrantes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submenuintegrantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/integrantes.png"))); // NOI18N
        submenuintegrantes.setText("Integrantes");
        submenuintegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuintegrantesActionPerformed(evt);
            }
        });
        menuacercade.add(submenuintegrantes);

        menuprincipal.add(menuacercade);

        menusalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        menusalir.setText("Salir          ");
        menusalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menusalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menusalirMouseClicked(evt);
            }
        });
        menuprincipal.add(menusalir);

        setJMenuBar(menuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuempleadosActionPerformed
     
                 Conexion conexion = new Conexion();
        
        //probamos si es diferente de vacio sera correcta la conexion
        if(conexion.conectar()!=null) {
            System.out.println("Conexion exitosa a tabla empleado ");
        }
        //sino la conexion no se ejecuto correctamente
        else {
            System.out.println("No se pudo hacer la conexion a tabla empleado");
        }
        
        Empleado modeloEmpleado = new Empleado();
        EmpleadoDAO modeloEmpleadoDAO = new EmpleadoDAO();
        FormEmpleado vistaEmpleado = new FormEmpleado();
        
        EmpleadoControlador controladorEmpleado = new EmpleadoControlador(modeloEmpleado, modeloEmpleadoDAO, vistaEmpleado);
        controladorEmpleado.iniciar();
        //vistaEmpleado.setVisible(true);
        CentrarVentanaInterna(vistaEmpleado);
        
    }//GEN-LAST:event_submenuempleadosActionPerformed

    private void submenuintegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuintegrantesActionPerformed
        // TODO add your handling code here:
        
        ImageIcon miicono = new ImageIcon(this.getClass().getResource("/imagenes/LOGO_SIC.jpg"));
         JOptionPane.showMessageDialog(null,"Dante Oswaldo Sánchez Castrejón\nRigoberto Lenin Sánchez Paredes\nCarlos Alberto Marquez Calderon\nLuis Miguel Dorantes Mendez","Integrantes del equipo",
                    JOptionPane.INFORMATION_MESSAGE,miicono);
    }//GEN-LAST:event_submenuintegrantesActionPerformed

    private void submenuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuclientesActionPerformed
        
        Cliente modeloCliente = new Cliente();
        ClienteDAO modeloClienteDAO = new ClienteDAO();
        FormCliente vistaCliente = new FormCliente();
        
        ClienteControlador controladorCliente = new ClienteControlador(modeloCliente, modeloClienteDAO, vistaCliente);
        controladorCliente.iniciar();
        //FormCliente cliente= new FormCliente();
        CentrarVentanaInterna(vistaCliente);
        
    }//GEN-LAST:event_submenuclientesActionPerformed

    private void menusalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menusalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menusalirMouseClicked

    private void submenuadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuadminActionPerformed
        // TODO add your handling code here:
        Administrador modeloAdmin = new Administrador();
        Empleado modeloEmpleado = new Empleado();
        EmpleadoDAO modeloEmpleadoDAO = new EmpleadoDAO();
        AdministradorDAO modeloAdminDAO = new AdministradorDAO();
        FormAdministrador vistaAdmin =  new FormAdministrador();
        
        AdminControlador controladorAdmin = new AdminControlador(modeloEmpleado, modeloEmpleadoDAO, modeloAdmin, modeloAdminDAO, vistaAdmin);
        controladorAdmin.iniciar();
        CentrarVentanaInterna(vistaAdmin);
    }//GEN-LAST:event_submenuadminActionPerformed

    private void submenuhabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuhabitacionActionPerformed
        // TODO add your handling code here:
        
              
        Habitacion modeloHabitacion = new Habitacion();
        HabitacionDAO modeloHabitacionDAO = new HabitacionDAO();
        FormHabitacion vistaHabitacion = new FormHabitacion();
        
        HabitacionControlador controladorHabitacion = new HabitacionControlador(modeloHabitacion, modeloHabitacionDAO, vistaHabitacion);
        controladorHabitacion.iniciar();
        CentrarVentanaInterna(vistaHabitacion);
    }//GEN-LAST:event_submenuhabitacionActionPerformed

    private void submenuservextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuservextraActionPerformed
       
        Servicio modeloServicio = new Servicio();
        ServicioDAO modeloServicioDAO = new ServicioDAO();
        FormServicio vistaServicio = new FormServicio();
        
        ServicioControlador controladorServicio = new ServicioControlador(modeloServicio, modeloServicioDAO, vistaServicio);
        controladorServicio.iniciar();
        CentrarVentanaInterna(vistaServicio);
        
        
    }//GEN-LAST:event_submenuservextraActionPerformed

    private void submenureservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenureservaActionPerformed
        // TODO add your handling code here:
        Reservacion modeloReserva = new Reservacion();
        ReservacionDAO modeloReservaDAO = new ReservacionDAO();
        FormReservacion vistaReserva = new FormReservacion();
        
        ReservaControlador controladorReserva = new ReservaControlador(modeloReserva, modeloReservaDAO, vistaReserva);
        controladorReserva.iniciar();
        CentrarVentanaInterna(vistaReserva);
    }//GEN-LAST:event_submenureservaActionPerformed

    
    public void CentrarVentanaInterna(JInternalFrame internalFrame) {
        
        int x = (ventanaprincipal.getWidth() / 2) - internalFrame.getWidth() /2;
        int y = (ventanaprincipal.getHeight()/ 2) - internalFrame.getHeight()/2;
        
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
            
        }else {
            ventanaprincipal.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lblacceso;
    public static javax.swing.JLabel lblacceso1;
    public static javax.swing.JLabel lblidempleado;
    public static javax.swing.JLabel lblidpersona;
    public static javax.swing.JLabel lblusuario;
    public static javax.swing.JLabel lblusuario2;
    public javax.swing.JMenu menuacercade;
    private javax.swing.JMenu menupersonal;
    public javax.swing.JMenuBar menuprincipal;
    public javax.swing.JMenu menureservaciones;
    public javax.swing.JMenu menusalir;
    public javax.swing.JMenu menuservicios;
    public javax.swing.JMenuItem submenuadmin;
    public javax.swing.JMenuItem submenuclientes;
    public javax.swing.JMenuItem submenuempleados;
    public javax.swing.JMenuItem submenuhabitacion;
    public javax.swing.JMenuItem submenuintegrantes;
    public javax.swing.JMenuItem submenureserva;
    public javax.swing.JMenuItem submenuservextra;
    public static javax.swing.JDesktopPane ventanaprincipal;
    // End of variables declaration//GEN-END:variables
}
